### ISSUE TITLE
[dcc32 Fatal Error] VSoft.HttpClient.pas(36): F2613 Unit 'VSoft.CancellationToken' not found.

### ISSUE THREAD

**Issue by beryindo** [VSoftTechnologies/VSoft.HttpClient#1]
[dcc32 Fatal Error] VSoft.HttpClient.pas(36): F2613 Unit 'VSoft.CancellationToken' not found.

**Comment by vincentparrett** [comment]
HTTP/2 is not currently supported. We use the microsoft WinHttp com interface, which doesn't currently support http/2 as far as I can tell. Even with their c++ api, http/2 is only partially supported (no multiplexing of requests as the api is not re-entrant).

**Comment by vincentparrett** [comment]
Moved issue to VSoft.HttpClient as that is what this issue is really about.

**Comment by beryindo** [comment]
> HTTP/2 is not currently supported. We use the microsoft WinHttp com interface, which doesn't currently support http/2 as far as I can tell. Even with their c++ api, http/2 is only partially supported (no multiplexing of requests as the api is not re-entrant).

now winhttp support HTTP/2 
https://docs.microsoft.com/en-us/windows/win32/winhttp/option-flags

**Comment by vincentparrett** [comment]
Not through the com api, at least I couln't find a way.
